blank_issues_enabled: false
contact_links:
  - name: Dúvidas Gerais
    url: https://github.com/carlapvicente/template-studies/discussions
    about: Por favor, faça perguntas e tire dúvidas na aba Discussions.