blank_issues_enabled: false
contact_links:
  - name: DÃºvidas Gerais
    url: https://github.com/carlapvicente/template-studies/discussions
    about: Por favor, faÃ§a perguntas e tire dÃºvidas na aba Discussions.
  - name: ğŸ” PolÃ­tica de SeguranÃ§a
    url: https://github.com/carlapvicente/template-studies/blob/main/SECURITY.md
    about: Consulte nossa polÃ­tica de seguranÃ§a e saiba como reportar vulnerabilidades.